apiVersion: apps/v1
kind: Deployment
metadata:
  name: 10519875-frontend
  
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: 10519875-frontend
  template:
    metadata:
      labels:
        deployment-name: 10519875-frontend
spec:
    containers:
      - name: 10519875-frontend
        image: ca-frontend #cab8it148.azurecr.io/10519875-frontend
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
labels:
   service-label: 10519875-frontend-cluster-service
name: 10519875-frontend-cluster-service

spec:
   type: ClusterIP
   ports:
     - name: 10519875-frontend-cluster-service-port
       port: 80
       protocol: TCP
   selector:
        deployment-name: 10519875-frontend
---
apiVersion: v1
kind: Service
metadata:
labels:
   service-label: 10519875-frontend-cluster-service
name: 10519875-frontend-cluster-service-loadbalancer

spec:
   type: LoadBalancer
   ports:
     - name: 10519875-frontend-load-balancer-service-port
       port: 80
       protocol: TCP
   selector:
        deployment-name: 10519875-frontend

        





